docker run -d \
--restart=always \
--name redis \
-p 6379:6379 \
-e REDIS_PASSWORD="123456" \
redis:latest


docker run -d \
--restart=always \
--name mysql \
-e MYSQL_ROOT_PASSWORD=123456 \
-e MYSQL_DATABASE=gin-admin \
-v mysql_data:/var/lib/mysql \
-p 3306:3306 \
mysql:5.7
